apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: projeto01
data:
  DB_HOST: "db.database.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "mensagensdb"
  API_HOST: "0.0.0.0"
  API_PORT: "5000"
