apiVersion: v1
kind: ConfigMap
metadata:
  name: projeto01-configmap
  namespace: projeto01
data:
  DB_HOST: "db"
  DB_PORT: "5432"
  DB_NAME: "mensagensdb"
  API_HOST: "0.0.0.0"
  API_PORT: "5000"
  VITE_API_URL: "http://localhost:7080"
